apiVersion: v1
kind: apiVersion: v1
kind: Namespace
metadata:
  name:  nginx 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  Namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: techpedia/nginx
        ports:
        - containerPort: 80
